apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - configmap.yaml
  - application-external-secrets.yaml
  - rbac.yaml
  - admission-policy.yaml
  - workload-admission-policy.yaml
  - runtime.yaml
  - validation-canary.yaml
  - openvpn.yaml
  - desktop-gateway.yaml
  - network-policies.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: codegate-range-runtime
    includeSelectors: false
    includeTemplates: true
