apiVersion: v1
kind: ServiceAccount
metadata:
  name: codegate-api
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: codegate-ai
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: codegate-web
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: codegate-grader
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: codegate-validator
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: codegate-telemetry
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: codegate-builder
automountServiceAccountToken: true
