- op: replace
  path: /spec/data
  value:
    - secretKey: MODEL_GATEWAY_INTERNAL_TOKEN
      remoteRef:
        key: codegate/production/internal/model-gateway
        property: token
    - secretKey: ANTHROPIC_API_KEY
      remoteRef:
        key: codegate/production/model-gateway/anthropic
        property: api-key
