import { createHash } from "node:crypto";

import type { BuildRecord, ResolvedPackage } from "./contracts.ts";
import { runtimeContractDigest } from "./runtime-contract.ts";

export const COMPONENT_POLICY_FILENAME = "codegate-component-policy.json";
export const COMPONENT_POLICY_DESTINATION = "/opt/codegate/component-policy.json";

export function renderControlledDockerfile(record: Pick<BuildRecord, "id" | "labId" | "labVersion" | "spec" | "specDigest" | "resolvedPackages">): string {
  const stages = record.resolvedPackages.map((item, index) => `FROM ${item.imageRef} AS package_${index}`);
  const copies = record.resolvedPackages.map((item, index) => renderPackageCopy(item, index));
  const artifacts = record.spec.target.artifacts.map((item) =>
    `ADD --link --checksum=sha256:${item.sha256} ${jsonInstruction([item.url, item.destination])}`,
  );
  const labels = [
    `LABEL org.opencontainers.image.title=${quoteLabel(record.spec.target.name)}`,
    `LABEL io.codegate.builder.version=\"1.0.0\"`,
    `LABEL io.codegate.build.id=${quoteLabel(record.id)}`,
    `LABEL io.codegate.lab.id=${quoteLabel(record.labId)}`,
    `LABEL io.codegate.lab.version=${quoteLabel(String(record.labVersion))}`,
    `LABEL io.codegate.spec.digest=${quoteLabel(record.specDigest)}`,
    `LABEL io.codegate.team=${quoteLabel(record.spec.team)}`,
    `LABEL io.codegate.runtime.contract=${quoteLabel(record.spec.target.runtimeContract.kind)}`,
    `LABEL io.codegate.runtime.contract.digest=${quoteLabel(runtimeContractDigest(record.spec.target.runtimeContract))}`,
    `LABEL io.codegate.runtime.uid=${quoteLabel(String(record.spec.target.runtimeContract.uid))}`,
    `LABEL io.codegate.runtime.port=${quoteLabel(String(record.spec.target.runtimeContract.port))}`,
    `LABEL io.codegate.component.policy.digest=${quoteLabel(componentPolicyDigest(record.resolvedPackages))}`,
  ];
  return [
    "# This file is generated by codegate-builder. User-provided Dockerfiles and commands are unsupported.",
    ...stages,
    `FROM ${record.spec.target.baseImage} AS target`,
    ...copies,
    ...artifacts,
    `COPY --link ${jsonInstruction([COMPONENT_POLICY_FILENAME, COMPONENT_POLICY_DESTINATION])}`,
    ...labels,
    "",
  ].join("\n");
}

export function renderComponentPolicy(packages: ResolvedPackage[]): string {
  const components = packages
    .map((item) => ({ componentId: item.name, runtimeKind: item.runtimeKind }))
    .sort((left, right) => left.componentId.localeCompare(right.componentId));
  return `${JSON.stringify({ schemaVersion: "codegate-component-policy/v1", components })}\n`;
}

export function componentPolicyDigest(packages: ResolvedPackage[]): `sha256:${string}` {
  return `sha256:${createHash("sha256").update(renderComponentPolicy(packages), "utf8").digest("hex")}`;
}

function renderPackageCopy(item: ResolvedPackage, index: number): string {
  return `COPY --link --from=package_${index} ${jsonInstruction([item.sourcePath, item.destination])}`;
}

function jsonInstruction(values: string[]): string {
  return JSON.stringify(values);
}

function quoteLabel(value: string): string {
  return JSON.stringify(value);
}

export function assertControlledDockerfile(value: string): void {
  const prohibited = /^\s*(?:RUN|CMD|ENTRYPOINT|SHELL|HEALTHCHECK|ONBUILD|EXPOSE|ENV|ARG|USER|WORKDIR|VOLUME)\b/im;
  if (prohibited.test(value)) throw new Error("Generated Dockerfile contains a prohibited instruction");
  if (/\$\{|`|\$\(/.test(value)) throw new Error("Generated Dockerfile contains interpolation syntax");
}
